/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Events: () => import('#controllers/events_controller'),
  Media: () => import('#controllers/media_controller'),
  Menus: () => import('#controllers/menus_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Stats: () => import('#controllers/stats_controller'),
}
